{% set name = "alps" %}
{% set version = "2.3.0" %}
{% set sha256 = "e64208d1e5acdd6f569277413c4867e1fa366cf4a224570eacbf1e9939fca2d2" %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://alps.comp-phys.org/static/software/releases/{{ name }}-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}
  patches:
    - remove_unit_testing.patch
    - skip_boost_numpy.patch
    - fix_skeleton.patch
    - no_python_extra_vars.patch
    - numpy_array_cdecl.patch
    - fix_xsl_padding.patch
    - remove_padding_from_prefix.patch
    - no_install_deplibs.patch  # [win]
    - boost_defs.patch  # [win]

build:
  # skip: true  # [not py27]
  number: 1005
  binary_relocation: False  # [osx]
  detect_binary_files_with_prefix: True
  features:
    - blas_{{blas}}     # [not win]


requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - icu  # [unix]
    - boost 1.65.1
    - python
    - numpy
    - scipy
    - hdf5 1.8.*
    - vs2008_express_vc_python_patch  # [win]
  run:
    - icu 58.*              # [unix]
    - boost 1.65.1
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - hdf5 1.8.*
    - blas 1.* {{blas}}     # [not win]

test:
  commands:
    - test -f $PREFIX/lib/libalps.dylib  # [osx]
    - test -f $PREFIX/lib/libalps.so     # [linux]
    - python -c "import pyalps"
    - python -c "import pyalps; print(pyalps.tools.xslPath())"
    - python -c "import pyalps; pyalps.copyStylesheet('.')"

about:
  home: http://alps.comp-phys.org/
  license: ALPS
  license_file: alps/LICENSE.txt
  summary: 'Algorithms and Libraries for Physics Simulations'

  description: |
    The ALPS project (Algorithms and Libraries for Physics Simulations) is an
    open-source effort aiming at providing high-end simulation codes for strongly
    correlated quantum mechanical systems as well as C++ libraries for simplifying
    the development of such code. ALPS strives to increase software reuse in the
    physics community.
  dev_url: https://alps.comp-phys.org/trac

extra:
  recipe-maintainers:
    - dolfim
